#! /bin/bash

set -ex

# If desired,  $1 can override the default image type
export IMAGE_ID=${1:-${NOTEBOOK_ID}}

printenv | sort

# image-login

export DOCKER_BUILDKIT=1

if [[ "$(which trivy)" == "" ]]; then
    "$CONDA_VER" install trivy
fi

# Scanning image with trivy. https://aquasecurity.github.io/trivy/

# docker run -v /var/run/docker.sock:/var/run/docker.sock \
#       public.ecr.aws/aquasecurity/trivy:latest \
trivy  image ${IMAGE_ID} \
       --timeout 30m \
       --severity HIGH,CRITICAL \
       --scanners vuln \
       --pkg-types os,library \
       --exit-code 1
