#! /bin/bash

set -ex

# If desired,  $1 can override the default image type
export IMAGE_ID=${1:-${NOTEBOOK_ID}}
export AGREE_TO_INSTALL=${2:-""}

printenv | sort

# image-login

export DOCKER_BUILDKIT=1

if [[ "$(which trivy)" == "" ]]; then
    echo "The 'trivy' scanner program is not installed,  installing."
    if [[ "$(which micromamba)" != "" ]]; then
        MAMBA=micromamba
    elif [[ "$(which mamba)" != "" ]]; then
        MAMBA=mamba
    elif [[ "$(which conda)" != "" ]]; then
        MAMBA=conda
    else
        curl -Ls micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
        MAMBA=bin/micromamba
        AGREE_TO_INSTALL="--yes"
        chmod +x ${MAMBA}
        eval "$(bin/micromamba shell hook --shell bash)"
        ${MAMBA} config append channels conda-forge
        ${MAMBA} config set channel_priority strict
        ${MAMBA} self-update
    fi
    ${MAMBA} install ${AGREE_TO_INSTALL} trivy
fi


# Scanning image with trivy. https://aquasecurity.github.io/trivy/

# docker run -v /var/run/docker.sock:/var/run/docker.sock \
#       public.ecr.aws/aquasecurity/trivy:latest \
trivy  image ${IMAGE_ID} \
       --timeout 30m \
       --severity HIGH,CRITICAL \
       --scanners vuln \
       --pkg-types os,library \
       --exit-code 1
