#! /bin/bash

set -eu

cd $JUPYTERHUB_DIR/scripts

case $(uname) in
     Linux)
        sudo apt-get -y update
        sudo apt-get -y install skopeo wget
        ;;
     Darwin)
        brew install skopeo
        ;;
     *)
        echo "Cannot suport required skopeo tool on your OS."
        ;;
esac

case $(uname) in
     Linux)
        wget https://github.com/orf/docker-repack/releases/download/v0.5.0/docker-repack-Linux-x86_64.tar.gz
        tar zxf docker-repack-Linux-x86_64.tar.gz
        rm docker-repack-Linux-x86_64.tar.gz
        ;;
     Darwin)
        wget https://github.com/orf/docker-repack/releases/download/v0.5.0/docker-repack-Darwin-x86_64.tar.gz
        tar zxf docker-repack-Darwin-x86_64.tar.gz
        rm zxf docker-repack-Darwin-x86_64.tar.gz
        ;;
     *)
        echo "Cannot suport required docker-repack tool on your OS."
        ;;
esac
