#! /bin/bash

set -eu

cd $JUPYTERHUB_DIR/scripts

if [[ "$(which skopeo)" == "" ]; then
    echo "skopeo missing,  installing in scripts directory"
    case $(uname) in
         Linux)
            sudo apt-get -y update
            sudo apt-get -y install skopeo wget
            ;;
         Darwin)
            brew install skopeo
            ;;
         *)
            echo "Cannot suport required skopeo tool on your OS."
            ;;
    esac
fi


if [[ "$(which docker-repack)" == "" ]; then
    echo "docker-repack missing,  installing in scripts directory"
    case $(uname) in
         Linux)
            rm -f docker-repack-Linux-x86_64.tar.gz
            wget https://github.com/orf/docker-repack/releases/download/v0.5.0/docker-repack-Linux-x86_64.tar.gz
            tar zxf docker-repack-Linux-x86_64.tar.gz
            rm -f docker-repack-Linux-x86_64.tar.gz
            ;;
         Darwin)
            rm -f docker-repack-Darwin-x86_64.tar.gz
            wget https://github.com/orf/docker-repack/releases/download/v0.5.0/docker-repack-Darwin-x86_64.tar.gz
            tar zxf docker-repack-Darwin-x86_64.tar.gz
            rm -f docker-repack-Darwin-x86_64.tar.gz
            ;;
         *)
            echo "Cannot suport required docker-repack tool on your OS."
            ;;
    esac
fi
