#! /bin/bash

set -o pipefail
set -e

cd $JUPYTERHUB_DIR
NBW_WRANGLER_SPEC=$(find nbw-spec-archive/ -name "*.yaml" -type f | sort | tail -1)
python -m nb_wrangler ${NBW_WRANGLER_SPEC} --validate --verbose
cp -v ${NBW_WRANGLER_SPEC} deployments/wrangler/environments/nbw-wrangler-spec.yaml
# source deployments/common/nb-wrangler.rc
# source ./nb-wrangler environment
