name: Notebook Curator Build
on:
   pull_request:
      branches:
        - main
      paths:
        - "nbc-spec-archive/**"
jobs:
  docker:
    name: Notebook Curator Ingest
    runs-on: ubuntu-24.04
    permissions:
        packages: write
        # contents: write
        # pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Configure
        shell: bash
        run: |
          git config --global user.email "dmd_octarine@stsci.edu"
          git config --global user.name "Curator workflow"
          scripts/image-configure curator --base-notebook minimal-notebook

      - name: Debug branch and files
        run: |
          echo "Current branch: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          echo "PR number: ${{ github.event.number }}"
          echo "HEAD commit: ${{ github.sha }}"

          # Show all files in the repository
          echo "All files in repo:"
          find . -type f | head -20

          # Show nbc-spec-archive directory contents
          echo "Contents of nbc-spec-archive:"
          if [ -d "nbc-spec-archive" ]; then
            ls -la nbc-spec-archive/
          else
            echo "Directory nbc-spec-archive does not exist"
          fi

          # Show git status
          git status

          # Show recent commits
          git log --oneline -5

      - name: Check for YAML files in nbc-spec-archive
        run: |
          if [ -d "nbc-spec-archive" ]; then
            echo "Found nbc-spec-archive directory"
            echo "YAML files:"
            find nbc-spec-archive/ -name "*.yaml" -type f
            echo "Total YAML files: $(find nbc-spec-archive/ -name "*.yaml" -type f | wc -l)"
          else
            echo "ERROR: nbc-spec-archive directory does not exist"
            exit 1
          fi

      - name: Set Up Environment
        shell: bash
        run: |
          pip install -r requirements.txt
          pip install git+https://github.com/spacetelescope/nb-curator.git
          curl https://raw.githubusercontent.com/spacetelescope/nb-curator/refs/heads/main/nb-curator >nb-curator
          chmod +x nb-curator
          ./nb-curator bootstrap
          sudo apt-get install gh

      - name: Free Disk Space,  Enlarge Swapfile
        shell: bash
        run: |
          df -h
          sudo apt clean
          # docker rmi $(docker image ls -aq)
          # docker container prune -f
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo fallocate -l 24G /swapfile
          sudo chmod 0600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          cat /proc/meminfo
          df -h

      - name: Validate Spec
        shell: bash
        run: |
          NBC_CURATOR_SPEC=$(find nbc-spec-archive/ -name "*.yaml" -type f | head -1)
          source ./nb-curator environment
          ./nb-curator $NBC_CURATOR_SPEC --validate --verbose

      - name: Validate Repo Changes
        shell: bash
        run: |
            # Change set can add one and only one spec
            if git diff --name-status HEAD^ HEAD | grep -v -E 'A\s+nbc-spec-archive/nbc-.*\.yaml'; then
                echo "PR change set includes more than a single curator spec, REJECTED."
                false
            fi

      - name: Install Curator Spec
        shell: bash
        run: |
            NBC_CURATOR_SPEC=$(find nbc-spec-archive/ -name "*.yaml" -type f | head -1)
            cp ${NBC_CURATOR_SPEC} deployments/curator/environments/nbc-curator-spec.yaml

    #   - name: Merge Pull Request via gh
    #     env:
    #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     run: |
    #         gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch

    #   - name: Checkout merged target branch
    #     uses: actions/checkout@v4
    #     with:
    #       ref: ${{ github.base_ref }}   # The target branch of the merged PR
    #       fetch-depth: 0

    #   - name: Update branch to latest commit (redundancy/safety)
    #     run: git pull origin ${{ github.base_ref }}

    #   - name: Archive Curator Spec
    #     shell: bash
    #     run: |
    #         NBC_CURATOR_SPEC=$(echo .nbc-spec-ingest/*.yaml)
    #         ARCHIVED_SPEC="nbc-spec-archive/$(basename $NBC_CURATOR_SPEC)"
    #         cp ${NBC_CURATOR_SPEC} deployments/curator/environments/nb-curator-spec.yaml
    #         git add deployments/curator/environments
    #         git mv $NBC_CURATOR_SPEC $ARCHIVED_SPEC
    #         git commit -m "Archived $ARCHIVED_SPEC. Added to curator environments."
    #         git push origin nbc-archive
    #         # gh pr create --base main --title "Archive Curator Spec" --body
    #         # PR_NUMBER=$(gh pr list --head <branch> --json number --jq '..number')
    #         # gh pr merge ${PR_NUMBER} --merge --delete

      - name: Image Build
        shell: bash
        run: |
           source setup-env
           scripts/image-build
           df -h
           docker system df
           docker system prune
           docker image ls
           df -h

      - name: Image Functional Tests
        shell: bash
        run: |
           df -h
           source setup-env
           scripts/image-test
           df -h

      - name: Image Push
        shell: bash
        run: |
            source setup-env
            docker tag $(docker image ls | head -2 | awk '{print $3;}' | tail -1)  ${GITHUB_IMAGE_ID}
            docker push $GITHUB_IMAGE_ID

      - name: Image Repack Slim
        shell: bash
        run: |
            source setup-env
            image-repack $NOTEBOOK_ID

      -name: Slim Image Push
            docker tag $(docker image ls | head -2 | awk '{print $3;}' | tail -1)  ${GITHUB_IMAGE_ID_SLIM}
            docker push $GITHUB_IMAGE_ID_SLIM

      # XXXX Trivy missing config to run from built image, fails
      # ----- - name: Run Trivy vulnerability scanner on image
      # -----   uses: aquasecurity/trivy-action@master
      # -----   with:
      # -----     scan-type: image
      # -----     image-ref: notebook-${{ matrix.DEPLOYMENT_NAME }}
      # -----     ignore-unfixed: true
      # -----     format: table
      # -----     vuln-type: os,library
      # -----     severity: 'CRITICAL,HIGH,MEDIUM'
