name: Code Quality
on:
   schedule: # weekly
     - cron: '0 0 * * 0'
   push:
   workflow_dispatch:

jobs:
  quality-scanning:
    name: "Code Quality -- All"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set Up Environment
        shell: bash
        run: |
           scripts/image-configure curator
           pip install -r requirements.txt
           df -h

      - name: YAML Parsing
        shell: bash
        continue-on-error: false
        run: |
           source setup-env
           scripts/sscan-yaml `find deployments .github scripts -name '*.yaml' -o -name '*.yml'`

      - name: Flake8 Scan
        shell: bash
        continue-on-error: false
        run: |
           source setup-env
           scripts/sscan-flake8

      - name: Ruff Scan
        shell: bash
        continue-on-error: false
        run: |
           source setup-env
           scripts/sscan-ruff
